kind: Service                             
apiVersion: v1
metadata:
  name: nginx
  namespace: nginx
  lables: 
    app: nginx
spec:
  type: NodePort
  ports:
      port: 80                               
      nodePort: 30225                    
  selector:
    name: nginx 
